# Generated by Django 4.2.7 on 2025-08-31 14:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gift_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftlist',
            name='fixed_contribution_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed contribution amount (for money collection lists)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='giftlist',
            name='list_type',
            field=models.CharField(choices=[('money_collection', 'Raccolta Soldi'), ('product_list', 'Lista Prodotti')], default='money_collection', help_text='Type of gift list', max_length=20),
        ),
        migrations.AddField(
            model_name='giftlist',
            name='max_contributors',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of contributors (for money collection lists)', null=True),
        ),
        migrations.CreateModel(
            name='GiftListProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('image_url', models.URLField(blank=True, help_text='Product image URL', null=True)),
                ('status', models.CharField(choices=[('available', 'Disponibile'), ('purchased', 'Acquistato'), ('reserved', 'Riservato')], default='available', help_text='Product status', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('purchased_by', models.CharField(blank=True, help_text='Name of person who purchased this product', max_length=255, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, help_text='When this product was purchased', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift_list', models.ForeignKey(help_text='Gift list this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='gift_lists.giftlist')),
            ],
            options={
                'verbose_name': 'Gift List Product',
                'verbose_name_plural': 'Gift List Products',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Specific product being purchased (for product lists)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='gift_lists.giftlistproduct'),
        ),
    ]
