# Generated by Django 4.2.7 on 2025-11-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_lists', '0002_giftlist_fixed_contribution_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftlist',
            name='show_in_public_gallery',
            field=models.BooleanField(default=False, help_text='Whether to show this list in the public gallery at /lists'),
        ),
    ]
