# Generated by Django 4.2.7 on 2025-12-01 23:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_lists', '0003_add_show_in_public_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftlist',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target amount to raise (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
